### ISSUE TITLE
cannot set module Output Cache Provider to None

### ISSUE THREAD

**Issue by fprati** [DNNCommunity/DNN.FormAndList#10]
The module suggests to set the cache settings to "None", but it is not saved. It is not just a performance detail because as a result we observe this issue: https://github.com/DNNCommunity/DNN.FormAndList/issues/9

**Comment by valadas** [comment]
@DNNCommunity/module-dev-team, @fprati 
I don't think this was causing issue #9 , the pipes in the title where causing that one.
Also, correct me if I am wrong, but I think the selection of cache providers is part of Dnn and not the module. What I think happens here is that it inherits the module cache setting form the host settings and can only be ovewritten if the cache duration is set to more than 0 seconds. So either way there should be no caching.

Also, the message is a bit confusing in recommending to set it to none, it should say to leave the duration at 0 seconds instead, but again I think that comes from Dnn itself right?

So I am closing this but feel free to reopen if I am wrong.
