### ISSUE TITLE
Bug in module Form&List dnn 9.11

### ISSUE THREAD

**Issue by meffj00** [DNNCommunity/DNN.FormAndList#103]
DNN version 9.11. 
a. authorized user is notified that she is not authorized
b. if you delete 1 file from a folder, the entire folder including its contents will be deleted;
c. Previously created documents can no longer be opened

**Comment by WillStrohl** [comment]
Thank you for reporting this potential bug.  I have a few follow-up questions.  I hope you don't mind... 

Which version of Forms and List is this that you're using? 
What kind of folder is it that this happens to, or does it not matter?  
What level is the folder in that this happens to?  Is it in the root, a subfolder, or either/both?

**Comment by meffj00** [comment]
Of course you can ask questions Will.
We are using Form and List version 6.5.5 on DNN platform 9.11.
We use a standard folder created by ourselves with the Resource manager.
In this case it was a subfolder ([root]\400_organisatie\mdz\ovl_mdz_dir\2022\...)

**Comment by valadas** [comment]
@meffj00 I am very unclear on steps to reproduce, if you can add a step-by-step from scratch to make this happen, I'll be happy to re-open this issue.
