### ISSUE TITLE
For a form type, how to limit permissions to edit/delete/list records only.

### ISSUE THREAD

**Issue by shash99** [DNNCommunity/DNN.FormAndList#105]
## Describe the bug
For a form type module.  I want users to be able to edit/delete and list entries submitted only.  If I give them edit content permission it gives them the ability to edit module settings and form and list configuration.

## To Reproduce
1. Go to form type module
2. Click on settings/permissionts
3. Set permissions as follows
4. 
![image](https://github.com/DNNCommunity/DNN.FormAndList/assets/5889823/e661b785-c9bc-4207-8bea-9cbbe4237bff)

these settings do not allow the user with the granted permission to be able to list the records when in edit mode.

## Expected behavior
I expect the user with the granted permission to be able to list records submitted.  Also edit and delete them.

**Comment by valadas** [comment]
I don't think this is a currently supported feature, if anyone has a clue, happy to re-open this issue.
