### ISSUE TITLE
Hide Submit/Cancel Buttons for the Users 

### ISSUE THREAD

**Issue by maduranga001** [DNNCommunity/DNN.FormAndList#106]
We are using FormAndList_06.05.05 on DNN 9.13
"Form below List" Option

We want to give the form submission option only for admins and need to hide the form from the users.
I changed the permission and it hid the form fields. But Still, the Submit/Cancel buttons are there. I is still appears as disabled buttons. But it is not the perfect way.
Please, let me know how to hide the buttons for the users and display them only for the admins.

Thank you!

**Comment by valadas** [comment]
If you don't always show the form then you get edit icons and "Add New Record" instead of the form always visible and that won't display to visitors
