### ISSUE TITLE
Save DNN Page link

### ISSUE THREAD

**Issue by maduranga001** [DNNCommunity/DNN.FormAndList#112]
DNN 9.13.4
FNL 6.5.8

I use URL field to select existing DNN pages. But it saved the tab ID. How can I save the page link to the database UserDefinedData table? I need to get this and show it back via an SQL to display in a chart. So I need it to save as the URL.

How can I do this? Please, can you help?

Thank you!

**Comment by valadas** [comment]
You could do a join on the TabId and the TabPath from the Tabs table potentially and then you can get the portal alias too by using the portalId of that tab and the PortalAliases table...
