### ISSUE TITLE
FnL 6.2.0 on DNN 8: Results are not displayed 

### ISSUE THREAD

**Issue by sleupold** [DNNCommunity/DNN.FormAndList#12]
In form mode, there is an option to display all records, which is simply not working in this version. No error logged.

**Comment by DotNetNuclear** [comment]
Sebastian, I confirmed the "Show Records" button at the bottom of the Form view does the same thing as the "Show Records" module action menu item.  It should redirect you to the /show/records List module view.  It works for me.  Can you provide any more details?

**Comment by SCullman** [comment]
CANNOT reproduce

**Comment by valadas** [comment]
I cannot reproduce in latest build either, I will close this, @sleupold feel free to reopen or submit a new issue if not resolved
