### ISSUE TITLE
FnL 6.2.0 on DNN 8: Search box not displayed

### ISSUE THREAD

**Issue by sleupold** [DNNCommunity/DNN.FormAndList#13]
if FnL is in List mode with Grid display type, and "show search box" (even with "show simple search") option selected, there is still no search input box displayed.

**Comment by DotNetNuclear** [comment]
Sebastian, the search box shows if you have it enabled in the settings AND you have at least one field in the form marked as "Searchable".   I understand this may not be obvious so I will take any recommendations as to how to improve it.

**Comment by sleupold** [comment]
yes, there are a number of columns marked as searchable (text columns, which are marked as searchable by default). I didn't notice this behavior in DNN 7.

**Comment by SCullman** [comment]
CANNOT reproduce

**Comment by valadas** [comment]
Looks like it is working fine in latest version, I am closing this.
