### ISSUE TITLE
Export CSV needs Created At Field

### ISSUE THREAD

**Issue by ufoloko** [DNNCommunity/DNN.FormAndList#16]
Please add Created At Field into CSV File.

**Comment by valadas** [comment]
In the spirit of cleaning the backlog I am closing this issue as nobody submitted a PR and the issue has been here multiple years.

**Comment by ufoloko** [comment]
> In the spirit of cleaning the backlog I am closing this issue as nobody submitted a PR and the issue has been here multiple years.

Please reopen this case too, im trying to finishing too.

I request your opinion too. I can add date for all reports, this can just need comment some lines, of maybe we can add a settings option to add or not date for reports. What do you think ?

**Comment by valadas** [comment]
Reopening as per comment above. In my opinion a setting could be nice to not break maybe some implementations what have done some automations with such csv exports. But I don't think it's critical either. Depends how much time you have...

**Comment by ufoloko** [comment]
Hi everyone this was added with my last pull request #88

**Comment by valadas** [comment]
Closing this issue as the PR is merged
