### ISSUE TITLE
"Show Records" gets a "Data Binding Failed" after 5000 records.

### ISSUE THREAD

**Issue by ackered** [DNNCommunity/DNN.FormAndList#17]
"Show Records" gets a "Data Binding Failed" after 5000 records.

Is there a limit to how many records can stay in a single Form and List module? I noticed that I get a Data Binding Failed message after I have crested over 5,000 records.

**Comment by ackered** [comment]
Any help?

**Comment by SCullman** [comment]
There is no limit - but the server might time out. 
FnL is not designed to handle thousands of records in one instance.

**Comment by valadas** [comment]
I agree with @SCullman this would be a major redesign of the module on all levels. I gonna go ahead and close this issue but if anyone @DNNCommunity/module-dev-team has an idea or wants to discuss a solution, please let me know and we can reopen this.
