### ISSUE TITLE
DNN9 and FormAndList module

### ISSUE THREAD

**Issue by GlantonHub** [DNNCommunity/DNN.FormAndList#18]
I have tried to install the module on DNN 9 instance but I get errors, is the module DNN 9 compatible? 

Error I get "Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Value cannot be null. Parameter name: type ---> System.ArgumentNullException: Value cannot be null. Parameter name: type at System.Activator.CreateInstance(Type type, Boolean nonPublic) at System.Activator.CreateInstance(Type type) at DotNetNuke.Modules.UserDefinedTable.DataType.get_DataTypes() at DotNetNuke.Modules.UserDefinedTable.DataType.SystemDataTypes() at DotNetNuke.Modules.UserDefinedTable.Components.FieldController.GetFieldsTable(Int32 moduleId, Boolean addNewColumn, Boolean addAuditColumns) at DotNetNuke.Modules.UserDefinedTable.Configuration.BindSettings() at DotNetNuke.Modules.UserDefinedTable.Configuration.Page_Load(Object sender, EventArgs e) --- End of inner exception stack trace ---"

Many thanks
A

**Comment by IbrahimYM** [comment]
I got this error as well.  I just refreshed the page and the error went away and I was able to create the form..  This should still be addresses

**Comment by jac69** [comment]
So is it compatible with DNN9?

**Comment by SCullman** [comment]
FormAndList_06.02.00 was broken because of a typo in datatypes.config.

**Comment by valadas** [comment]
@EPTamminga can you please close this issue since it is resolved. Thanks
