### ISSUE TITLE
DNN 8.0.0/.NET 4.5 release

### ISSUE THREAD

**Issue by RSSLLC** [DNNCommunity/DNN.FormAndList#2]
Hi, can the changes from the pull requests area be placed into a version 6.2.0 release of the Form and List module so that it will be compatible with DNN 8.0.0/NET 4.5?  Thanks!  Todd

**Comment by EPTamminga** [comment]
I created a new release for DNN8. Please note that this version has not been extensively tested (I do not have a full test environment for F&L available).

**Comment by RSSLLC** [comment]
Thank you, very much appreciated.  We will do some detailed testing.

**Comment by RSSLLC** [comment]
Hi Ernst, thanks again for updating the FnL module!  I did notice one defect, but I suspect it may not be tied to just the newest version.  When the extension is first installed and then placed on a page for the first time, it throws an exception when the "Configuration" button is clicked.  At that point, you can return to the first dialog and click the Configuration button again and it looks to run properly.  I've attached a few screenshots for reference in case you want to address in a future version.  Todd
![fnl-new-install-screenshot-1](https://cloud.githubusercontent.com/assets/17261388/13539127/7ce3b5ae-e21c-11e5-8cff-6820935efb13.jpg)
![fnl-new-install-screenshot-2](https://cloud.githubusercontent.com/assets/17261388/13539136/81c90ccc-e21c-11e5-9ee1-e150bcdc6e49.jpg)
![fnl-new-install-screenshot-3](https://cloud.githubusercontent.com/assets/17261388/13539138/84adbb72-e21c-11e5-973d-7ef253cad591.jpg)
