### ISSUE TITLE
Please add a file upload field

### ISSUE THREAD

**Issue by ufoloko** [DNNCommunity/DNN.FormAndList#20]
It would be great to have an option to upload a file in form and list module

**Comment by SCullman** [comment]
This requires a lot of work. I sketched a way to do that years ago, but I would really recommend using an other tool (e.g.[ 2sxc with mobius forms](https://2sxc.org/en/blog/post/releasing-mobius-forms-2-with-file-upload-and-koi))

**Comment by valadas** [comment]
There is the image and download data types that allow uploading, I don't understand the use case here @ufoloko can you elaborate?

**Comment by SCullman** [comment]
It is most likely about uploading files from unauthenticated users. There are many of them: Documents (certificates, CVs), pictures, etc. Since the request is not authenticated, there is no user folder for saving these files. DNN also has no mechanism for this that could be adopted.

**Comment by valadas** [comment]
Although not impossible, I think it would be a security risk and spam risk. I don't think we here want to get into that. If someone @DNNCommunity/module-dev-team wants to tackle this, please re-open.

**Comment by ufoloko** [comment]
Hi to all, i was talking about SCullman feature, sometimes is needed to have a form with an option to upload and send a file (photo, pdf, certificate, CVs, etc).

Im know there is a security and spam risk, but maybe with some little additional control like regular expression for filename can solve a little this.

Additionally with this we can have a captcha file, to avoid spam, this can solve problems for any form.
