### ISSUE TITLE
When using form templates, cant use captcha control on form

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNN.FormAndList#21]

**Comment by SCullman** [comment]
Well, it is possible, but the form generator ignores the captcha. But it can be included manually:

```
<div class="form-horizontal">
    <div class="form-group">
        <div class="col-md-2">[label-for:Test]</div>
        <div class="col-md-10">[editor-for:Test]</div>
    </div>
   <div class="form-group">
        <div class="col-md-2">Captcha</div>
        <div class="col-md-10">[editor-for:Security Code]</div>
    </div>
</div>
```
turns into 

![image](https://user-images.githubusercontent.com/5693190/41498103-2bb4c8c8-7165-11e8-8f95-2820173835b9.png)

**Comment by valadas** [comment]
I have resolved this issue in another way, also adding support for Google ReCaptcha, but I like that you can place it in your form template, I just learned that. But I think my implementation and this wont work together, I am testing... Would be nice to combine this token and still keep the Recaptcha option.

**Comment by valadas** [comment]
@SCullman Can you point me in the right direction here, where is [editor-for:Security Code] getting replaced by the captcha control?

**Comment by valadas** [comment]
@SCullman never mind, I found an issue where it was being added twice on the page from the last commit, I am working on it, I should be able to make both features work in #30 I am on it.

**Comment by SCullman** [comment]
@valadas in Form.ascx.cs, line 91.
It should be possible. The id of the captcha control is generated out of the title, in that case it is defined as "Security Code" within the resx file. Too much tricks, isn't it?

**Comment by valadas** [comment]
In the resx file, would'nt that break the form template if someone translates it?
