### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNN.FormAndList#32]
I have moved the documentation from codeplex to the project wiki here on github. I have made some _minor_ corrections but the documentation needs to be completely reviewed and updated.

**Comment by SCullman** [comment]
@valadas What do you think about moving the documentation into the github wiki?

**Comment by valadas** [comment]
@SCullman that is what I have done earlier today, it is already in the wiki. It need updating though, but it's a start. I have converted everything to Markdown, it was a mixbag in codeples. While doing that I cleaned up a bit of obvious stuff but it still needs more updating.

One think that I would have liked to add here is what was at http://www.formandlist.com/Documentation/CustomSearchwithRecordFilter.aspx 

Where you the one managing that site that no longer exists? If so it would be nice to bring that over to this documentation if you have a site archive or something...

**Comment by SCullman** [comment]
formandlist.com was managed by dnnwerk.de, and I don't have a copy. Maybe @sleupold can help.
I tried to recreate the page from waybackmachine though: https://github.com/DNNCommunity/DNN.FormAndList/wiki/Custom-Search

**Comment by valadas** [comment]
@SCullman Awesome, I did not think of that, good idea.

**Comment by sleupold** [comment]
I should be able to re-publish the site formandlist.com, please give me a few days...

**Comment by valadas** [comment]
@sleupold only if you think there is valuable information that is not already in the wiki.

**Comment by SCullman** [comment]
@sleupold I would appreciate if you republish it for a  few days. There had been a lot of tipps and tricks; and I would transfer the best of them to the wiki.

**Comment by valadas** [comment]
In the spirit of cleaning the backlog I am closing this issue as nobody submitted a PR and the issue has been here multiple years.
