### ISSUE TITLE
Error when create record

### ISSUE THREAD

**Issue by ufoloko** [DNNCommunity/DNN.FormAndList#41]
I installed last version 6.5 on DNN 8.0.4 and after set fields, when try to add a new record I’m receiving this error

Method not found: 'System.DateTime DotNetNuke.Common.Utilities.DateUtils.GetDatabaseUtcTime()

Please your help

**Comment by valadas** [comment]
Issue confirmed, GetDatabaseUtcTime only appeared in 9.1.0, this could be replaced with GetDatabaseTime which maps to it.

Also, when doing this, the module should be built on Dnn 8.0.4 references to make sure we don't have the same situation elsewhere in the code when the deprecated API calls where replaced.

**Comment by SCullman** [comment]
I always develop my modules in latest but reference dnn assemblies of the minimum target.

**Comment by valadas** [comment]
Yes, this was an error from me, I am too used to building very specific modules for a single customer and I forgot to reference an older version

**Comment by CubeDweller** [comment]
I too just installed version 6.5.0 on DNN 8.0.4 and have similar errors.
Both when adding a record and with XSL Transformation (.xsl)
Method not found: 'System.DateTime DotNetNuke.Common.Utilities.DateUtils.GetDatabaseUtcTime()'
Is this being fixed? ETA?
(Sorry if its rude to ask; but I'm new to GitHub and my project is roadblock by this issue.)
Thank you for your help.

**Comment by SCullman** [comment]
if you are in hurry, you have the following options:

- Upgrade to DNN9.1.0 (or better latest)
- or downgrade FnL to 6.4.0
- or fix the bug on your own and send a pull request.

**Comment by CubeDweller** [comment]
Thank you for responding SCullman .
Unfortunately dislike DNN9 and don't have the skills to fix the bug.
So I'll try the downgrade.
Question: Can you install an older version of an extension "over" a newer one?

**Comment by SCullman** [comment]
This depends on the extension. As long as the settings and database schema are the same, all you need is to replace the files (and assemblies). This should be the case for Fnl 6.4.0/6.5.0.

Procedure:   

1. Do a backup first, just to be sure!
1. Open Host-Extensions, edit _Form and List_
2. Goto section "Package Settings" and set the version number to _06.04.00_, save (button update extension)
3. Install FnL 6.4.0. It will ask you whether you wanna doe a repair installation. Click yes.
4. Done.

**Comment by CubeDweller** [comment]
Thank you SCullman.
(That looks very clever.)
I did successfully go through the steps; but the issues remained.
Just going to hold off for now and hope a fix is coming.

**Comment by stetard** [comment]
AFAIK DNN won't downgrade the dll which is present in the bin folder when repairing the module. Consequently, the dll version 6.5.0 will remain. I suggest you to manually overwrite the dll with the version 6.4.0.

**Comment by SCullman** [comment]
fixed with #45
