### ISSUE TITLE
Custom search options for FnL 6.1

### ISSUE THREAD

**Issue by rogerharness** [DNNCommunity/DNN.FormAndList#42]
Is there a way to create custom **search** options (check boxes, radio buttons, etc.) in Form and List, other than the default 'Browse records in...' dropdown / text boxes?

I'm trying to work my way through documentation re: XSLT, but I'm thinking this is only for displaying the results, but not how to give the user different options for searching/filtering those results?

Thank you!
-Roger Harness

**Comment by rogerharness** [comment]
Thanks for responding Stefan!

I'll definitely take a look at the other options you mentioned. We're currently a bit 'invested' in the FnL as we're using a few instances of it on our site, and other than this recent multiple search options request, we've been able to do most everything we want.

Do you happen to know of any other resources out there that might help me duct tape this thing together? The table is currently less than 200 records with only 4 added columns. We just want the user to be able to filter out the rows via some checkboxes, radio buttons etc.

![image](https://user-images.githubusercontent.com/42754758/44740379-2e71aa80-aaaf-11e8-8196-7ba66d491bb0.png)

Thank you again for the response Stefan,
-Roger Harness

**Comment by valadas** [comment]
I totally understand there is sometimes duct tape needs. If you do not need the search to be part of the urls, and the amount of data is not massive, you may consider rendering everything and then a piece of javascript for the actual searching, filtering. This example should get you started https://www.w3schools.com/howto/howto_js_filter_table.asp

**Comment by EPTamminga** [comment]
If you are willing to spend some money, DNNSharp has an excellent grid module.

**Comment by rogerharness** [comment]
Daniel and Ernst,

I'm going to look into both of these options...thank you very much!

-Roger Harness
