### ISSUE TITLE
CSS Style is not working and spacing issue with HTML data type

### ISSUE THREAD

**Issue by roostad** [DNNCommunity/DNN.FormAndList#46]
These issues are for Version 6.05:

1. The CSS Style Option is not functioning under the Form Settings (in the configuration menu) for the Text data type. For example, width:400px;min-width:400px has no effect on the column.

2. When setting a column to the HTML data type, there is additional padding added to cell height within the column when additional HTML tags/formatting are used. The expected behavior should be similar to the Text data type where cell height automatically adjusts depending on amount of text in cell (see attachment for example).
![module issue](https://user-images.githubusercontent.com/37156478/45521813-9ba26280-b774-11e8-933e-594a753df68d.jpg)

**Comment by SCullman** [comment]
Please create 2 issues for two separate concerns next time.

Anyway, I can't see anything wrong.
1. Can't reproduce as styles are injected to the input control.
2. There is no additional padding. The RTE wraps your content into a **p** tag. It is the burden of the (skin) designer to handle this.
