### ISSUE TITLE
UserDefindTable_GetRows Querry issue

### ISSUE THREAD

**Issue by HarrisCounty** [DNNCommunity/DNN.FormAndList#48]
We are using the form and list module in our DNN 9.1.1 platform and we have noticed that the query UserDefindTable_GetRows is running constantly on our database server and using 100% of the CPU. Can you please help us why this query is running constantly? our database team have suggested we index this query. can you tell us if this will help?

![userdefindtable_getrows_querry](https://user-images.githubusercontent.com/33842540/46560842-c9ce1a80-c8ba-11e8-9e27-f0deb26358cb.png)

**Comment by SCullman** [comment]
Give it a try and report whether it helped or not. I guess you can't make it worse.
