### ISSUE TITLE
Redirect to another page

### ISSUE THREAD

**Issue by deskpal** [DNNCommunity/DNN.FormAndList#49]
## Is your feature request related to a problem?
I would like to be able to redirect the form to another page after submitting. IT would work as a "thank you" page. It seems that this used to be possible in the past, but I couldn't find it on the latest version

**Comment by deskpal** [comment]
06.05.01 - @nvisionative  - I was not sure if this would be a new feature as I don't see this feature at all in the settings - So I thought it wouldn't be a bug, but a feature request.

**Comment by nvisionative** [comment]
@deskpal okay thanks - so I guess the real question here is "did this feature previously exist?"  The answer to that question I do not know.  I will ping some people and ask around though.  :)

**Comment by CBPSC** [comment]
Yes, this feature previously existed. See this screenshot of it.

![fnl](https://user-images.githubusercontent.com/4571863/47749991-ae112680-dc64-11e8-837c-f415d6fac96c.jpg)

**Comment by nvisionative** [comment]
Okay, now we are getting somewhere.  @deskpal what does the **Configuration** page have on it now?  I still see the relevant code in **configuration.ascx**, but have not done any local testing yet.

**Comment by deskpal** [comment]
This is all I see now @nvisionative 
![form-settings](https://user-images.githubusercontent.com/12358132/47751982-a2742e80-dc69-11e8-8dc8-97efc28524e7.PNG)

**Comment by nvisionative** [comment]
@deskpal what happens when you check **Enable Form Template**?

**Comment by SCullman** [comment]
Enable Form template has nothing to do with redirection. It is an ability to customize the UI of your form, but doesn't control further behaviour.

For Page Redirection  on submit, please switch Appeareance  to "Form".

![image](https://user-images.githubusercontent.com/5693190/47773293-e4dd5000-dce9-11e8-9e26-3b9c2dd29baa.png)

**Comment by nvisionative** [comment]
Sorry @SCullman - I am not very familiar with FormAndList - was just trying to help out @deskpal 
Thanks for chiming in!

**Comment by SCullman** [comment]
@nvisionative, @deskpal   no, let me thank you to you. 
This is a much better place to discuss as in Facebook, thank you for raising it at the correct place and doing "first level support".
Very much appreciated!

**Comment by nvisionative** [comment]
@SCullman thanks - it is really nice to see all the revitalized community dialogue and we want to help in any way we can.
