### ISSUE TITLE
Upgrade 6.1.0 -> 6.2.0 - datatype "calculated column" is missing

### ISSUE THREAD

**Issue by mcshorty** [DNNCommunity/DNN.FormAndList#5]
After upgrading from 6.1.0 -> 6.2.0 (DNN 8.0.1) the datatype "calculated column" is missing.

**Comment by sleupold** [comment]
this seems to be caused by a modified entry in dataType.config.
The last entry should be just   <dataType name="Expression" />

**Comment by SCullman** [comment]
Well, it should have been  
`<dataType name="Expression" typeName="DotNetNuke.Modules.UserDefinedTable.DataTypes.DataTypeExpessionEmail"/>`

**Comment by sleupold** [comment]
seem to be fixed by DNN Corp. already.

**Comment by SCullman** [comment]
FIXED

**Comment by valadas** [comment]
@EPTamminga , please close this one too
