### ISSUE TITLE
DatePicker not working in 6.05.01

### ISSUE THREAD

**Issue by reveriedax** [DNNCommunity/DNN.FormAndList#50]
There is an extra single quote in the resx file that is causing a javascript error which renders the datepicker nonfunctional. 

In App_LocalResources/form.ascx.resx, Monday has 2 leading single quotes, should be 1:

```
<data name="DayNamesMin.Text" xml:space="preserve">
    <value>'Su',''Mo','Tu','We','Th','Fr','Sa'</value>
  </data>
```

**Comment by SCullman** [comment]
Good catch!
