### ISSUE TITLE
Folder permissions, image type

### ISSUE THREAD

**Issue by TineHorvat** [DNNCommunity/DNN.FormAndList#51]
## Describe the bug
Hello,
I have one thing thats is buggering me for quite a few days now.
We have DNN 8.4.2 and the latest FNL 6.5.1.

Not sure if this is a bug or a feature by design or not even possible. We have setup the module definition to have two fields, one is string the other one is an image type. The idea behind the module is a  really simple one, add your own record with a description and an image of it. When you add it an admin or a host user needs to review or maybe change something and the save it again. So we have two user roles admins and registered users. A user can see only his files so we set the permissions to Portals/0/Users/ folder for role Registered users, other folders and hidden. This was set under Admin -> File management.

Everything OK so far.. when users chooses a folder to upload, he can only select "My Folder" (any idea where this is set what actually is My Folder, we found out its /portals/0/Users/[modulus]/[userid], but didn't found any settings to change to something else?).

**But the main problem is when and admin or even a host tries to edit the same record... he doesn't have the same file selected but the first file from root folder /portals/0/, so he can't edit another users record and the save it without overriding and changing the main image from the original record.**

Is this some kind of bug or a limitation of DNN file manager or something else? Can you please explain, pretty please :)

## To Reproduce
1. Add new module to page, set two fields one string, one image as the schema definition, make them both required.
2. Set the FNL settings to user can edit only his records. 
3. Create a regular user and log with him in another browser or incognito, on the first browser be logged in as host or admin account.
4. Create a record with a regular user and one record with admin/host user. Upload a file to My Folder/ as a regular user. choose any other folder and upload with admin/host user.
5. Now let admin edit the user created record and check what file is selected under image type field.
6. It is overridden with admin/hosts files and its actually not showing the users uploaded file.

## Expected behavior
An admin/host user can see, check or change or leave the users uploaded file. Not that it gets overridden by his files, especially not the first image type from /Portals/0/.

## Error log
There are no errors logged in the event viewer that I would know of.

I hope someone can check this or at least tell me that the expected behaviour is not even possible or am I doing something completely wrong? :\

Thanks for heads up and hope to hear from you soon.
Tine

**Comment by SCullman** [comment]
It is expected behavior by DNN. You cannot circumvent these limitations with FnL  Your use case is not supported.
