### ISSUE TITLE
Enabling Google recaptcha prevents email generation

### ISSUE THREAD

**Issue by fprati** [DNNCommunity/DNN.FormAndList#53]
When I enable google recaptcha through the module settings and try and submit the form (with successful recaptcha tick, obviously), the page refreshes, no email is generated and the following exceptions are generated in the event log:

ModuleControlSource:DesktopModules/UserDefinedTable/Default.ascx
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:1ac24bfc-e0b0-4a57-bb1f-9deddb15d40c
AssemblyVersion:9.2.2
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
ExceptionHash:K6Osw+Chpatou2xbo59P5eIcelY=
Message:The underlying connection was closed: An unexpected error occurred on a receive.
StackTrace:
InnerMessage:The underlying connection was closed: An unexpected error occurred on a receive.
InnerStackTrace:
at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request) at System.Net.WebClient.DownloadString(Uri address) at System.Net.WebClient.DownloadString(String address) at DotNetNuke.Modules.UserDefinedTable.Components.ReCaptcha.Validate(String encodedResponse, String privateKey) at DotNetNuke.Modules.UserDefinedTable.EditForm.cmdUpdate_Click(Object sender, EventArgs e)

--------------------

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:c4b8c63b-c42f-4e30-b7a8-f3512ab592ef
AssemblyVersion:9.2.2
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
ExceptionHash:wiYHrnELzOzA0mS+ldRz+Tgt8hg=
Message:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).
StackTrace:
InnerMessage:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).
InnerStackTrace:
at System.Web.UI.ControlCollection.Add(Control child) at DotNetNuke.Services.Exceptions.Exceptions.ProcessModuleLoadException(String FriendlyMessage, Control ctrl, Exception exc, Boolean DisplayErrorMessage)

-------------------

I obtained it on 2 different websites with different skins.
DNN version: 9.2.2
FNL versions: 6.5.0, 6.5.1, 6.5.2

**Comment by valadas** [comment]
Hi @fprati ,
Is the server behind a firewall that would prevent it from communicating with google for verification?
Is the server old? I think Google now require TLS1.2 Can you check the OS version and .Net framework updates ?

**Comment by fprati** [comment]
Hi Daniel,
the server is relatively recent and up to date, running Windows Server 2016, SQL Server 2017, IIS10.
The sslabs test confims TLS1.2: https://www.ssllabs.com/ssltest/analyze.html?d=air-ambulance.com

As for the firewall I read I must allow outgoing port 80 on all IPs. I verified I can connect to google.com and youtube from the server, is that good enough to prove that point? On the other hand I guess things like google analytics won't run either (although that's probably another kindof access).

**Comment by fprati** [comment]
and my .Net version is 4.7.2

**Comment by valadas** [comment]
Hmm, that is strange, I have it running on a couple sites without issues. Could you try a new empty site with the default skin and a very simple form with just one text field and recaptcha enabled. Just trying to rule out possibilities... Also, google recaptcha now has I think 4 versions of keys, something like V2-recaptcha, V2-no-captcha, V2 invisible, V3, can you try those variations maybe. And one last thing that comes to mind, you need to authorize the domain name with the key too.

**Comment by fprati** [comment]
I think I found out the cause of the issue: I had setup the server to use TLS 1.2 only and when I added TLS 1.0 and 1.1 it worked. Which means google recaptcha wants one of them and is not ready for TLS 1.2 (yet). Can you try and disable those lower protocols and see if you have the problem?
Cheers

**Comment by valadas** [comment]
According to this, recaptcha supports TLS 1.2 https://stackoverflow.com/questions/48156519/recaptcha-closing-underlying-connection

**Comment by fprati** [comment]
True, but it was only after I added 1.1/1.0 that it started to work. I used the IISCrypto utility to set it up (to avoid mistakes fiddling with the registry) and it was all verifed with SSLLabs.
I guess most people have such a configuration where they enable TLS 1.2, but don't disable the others, which is probably the default way of doing. I wanted to be a bit more aggressive and that's the result :(
