### ISSUE TITLE
Issue when you set a Required date field

### ISSUE THREAD

**Issue by ufoloko** [DNNCommunity/DNN.FormAndList#54]
If you set a Required Date Field, datepicker is not being initialized.

1.- Create a new Form
2.- Add a new Date field, but set as required field.
3.- Save an try to input a record.

## Expected behavior
When you focus date field you should see datepicker, but is not showinw

I can see problem is because class for date field when required is class="fnl-datepickerdnnFormRequired", so the script is not finding fnl-datepicker class to initialize, i think

**Comment by chadwixk** [comment]
Ditto. Same issue here.

**Comment by RockSolidSW** [comment]
Same issue here.  The icon to the right of the date and time fields no longer appear as well (at least in DNN 9.3.2).  Also, can we adjust things such that when date and time fields are required, they show the red vertical bar on the left hand side of the field?  Happy to help test a build, and we'll try to make the adjustments and submit if have a few spare minutes of dev time!
