### ISSUE TITLE
Add client side validation for fields

### ISSUE THREAD

**Issue by ufoloko** [DNNCommunity/DNN.FormAndList#55]
Actually, you have regular expression validator for fields but just works after submit the form

It would be great to have client side validations too, for better UX with forms.

**Comment by valadas** [comment]
In the spirit of cleaning the backlog I am closing this issue as nobody submitted a PR and the issue has been here more than a year.

**Comment by ufoloko** [comment]
> In the spirit of cleaning the backlog I am closing this issue as nobody submitted a PR and the issue has been here more than a year.

Hi Valadas, Im already working on this, can you reopen please, I think this can take me some days more to finish.

I would like to ask to somebody about the better way to make this change. To try to add the client side for each type(string, email, currency, etc) this requires duplicated code in each type or simply try to add this on Editcontrols file (this apply just for required field)

If somebody want to talk a little about it, please let me know.

**Comment by valadas** [comment]
Reopening the issue as per comment above.

**Comment by ufoloko** [comment]
I already sent a pull request with this feature

**Comment by valadas** [comment]
@ufoloko let me know if you still plan on working on this issue and I'll be happy to re-open.
