### ISSUE TITLE
Attempting to use Generated Bootstrap form Template Error

### ISSUE THREAD

**Issue by chadwixk** [DNNCommunity/DNN.FormAndList#57]
## Describe the bug
 
- Choose Enable Form Template, and use the Generate Template button
- Then when clicking on the Edit icon for a row in the list, the module throws an error and won't load

The template that was generated, if that helps, was this:
```
<div class="form-horizontal">
    <div class="form-group">
        <div class="col-md-2">[label-for:Open Date]</div>
        <div class="col-md-10">[editor-for:Open Date]</div>
    </div>
    <div class="form-group">
        <div class="col-md-2">[label-for:Project]</div>
        <div class="col-md-10">[editor-for:Project]</div>
    </div>
    <div class="form-group">
        <div class="col-md-2">[label-for:Status]</div>
        <div class="col-md-10">[editor-for:Status]</div>
    </div>
    <div class="form-group">
        <div class="col-md-2">[label-for:Complete Date]</div>
        <div class="col-md-10">[editor-for:Complete Date]</div>
    </div>
</div>
```

## Error log
ModuleId 441 ModuleDefId 136 FriendlyName ModuleControlSource DesktopModul 
ModuleId:441
ModuleDefId:136
FriendlyName:
ModuleControlSource:DesktopModules/UserDefinedTable/Form.ascx
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:0e4e615e-28f3-4611-b78c-d509ee1d97cd
AssemblyVersion:9.2.2
PortalId:0
UserId:1
TabId:43
RawUrl:/Projects/ctl/edit/mid/441?UserDefinedRowId=3
Referrer:https://leydenranch.org/Projects
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
ExceptionHash:MehwU+QEa/Gf9ncgirdVIflTa68=
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
at DotNetNuke.Modules.UserDefinedTable.DataTypes.EditString.set_Value(String value) at DotNetNuke.Modules.UserDefinedTable.EditForm.Page_Load(Object sender, EventArgs e)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: Mozzo-VM-App-DB

**Comment by SCullman** [comment]
I cannot reproduce your issue.

**Comment by valadas** [comment]
I was also not able to reproduce the issue, if you have any other steps to reproduce this issue, please add comments or open a new issue with more steps to make it happen
