### ISSUE TITLE
DNN 9 Form and List Configuration

### ISSUE THREAD

**Issue by ebirien** [DNNCommunity/DNN.FormAndList#61]
I have recently upgraded a dnn 6.2.3 site with F&L 6.1.0 to dnn 9.2.2 and F&L 6.5.2. Unfortunately the F&L configuration shows the following error message which does not allow users to update existing records or add a new record:
"DataType "Tags" is not installed. Please either check DataTypes.Config or change the type of the matching fields."
 
I have observed that the reason for this error is because "Tags" has been removed from the List of form control types of F&L version 06.05.02.

I strongly believe including Tags in the available forms controls list will resolve this issue.

Please find the screen shot of the issue below:

![issue-screenshot](https://user-images.githubusercontent.com/6187550/56896093-bf57b600-6a82-11e9-9d9c-44e481cfd24e.png)

**Comment by SCullman** [comment]
@ebrien, Tags looks like a custom datatype, which was never part of the FnL Distribution. 
The datatype itself is NOT reomved, but it is not listed anymore within the Datatype.config file. That file is always overwritten during an update. 
As that datatype is a custom extension, I cannot tell you what to enter. Please retrieve an older version of Datatype.config from a backup and copy that missing line.

**Comment by ebirien** [comment]
Many thanks, Stefan for your quick response.
This issue is now resolved and closed
