### ISSUE TITLE
DNN 9.2.2 and FormAndList module 6.5.2

### ISSUE THREAD

**Issue by ebirien** [DNNCommunity/DNN.FormAndList#62]
Following Stefan's advise I was able to Tags - a custom datatype to the list of datatypes. And I'm able to make Tags selections but clicking on any form control that causes page postback [File (A File on Your Site)] clears multi-select Tags text boxes. All other input form controls, including single-select Tags input control retain their input data on page postback.

See "Before PostBack" the screen below:

![beforepostback](https://user-images.githubusercontent.com/6187550/57069350-49468f80-6ccc-11e9-888e-ef609a984fa6.png)

See "After PostBack" the screen below:

![afterpostback](https://user-images.githubusercontent.com/6187550/57069362-53688e00-6ccc-11e9-8603-af9fe6be0661.png)

I'll appreciate any suggestion that will help me to fix this issue. I want the data in all input form controls to be available when the "Update" button is clicked.

**Comment by ebirien** [comment]
Can somebody please help me.

Prior to upgrading from dnn 06.02.03 and F&L 06.01.00,  to dnn 09.02.02 and F&L 06.05.02, this postback issue was not there. What could be causing this problem?

Many thanks in advance.

**Comment by BrianBakewell** [comment]
We are having this issue and any help would be greatly appriciated.

**Comment by BrianBakewell** [comment]
I have found a work around, but this will take a lot of work. 
By creating a Form Template and then from this you can add ASP:UpdatePanels' arround the fields that post back. This will mean that the postback is limited to just that element and the Tags are not removed.
The only issue with this is that it needs to be done on every page that has the Form and List module which for our site will be over 1000 pages. 
Does anyone know of a different way of doing this like creating a standard template or being about to add the update panel a different way?

**Comment by BrianBakewell** [comment]
I have resovled this with the following.

On one of the Form Templates I have ticked the box to say Enable Form Template and then Generated Template with the "Generate Template (optimized for Bootstrap)" button.

I have modified the skin to use Bootstrap and then Modified the Generated Template putting the following code arround the postback elements:

<asp:UpdatePanel ID="PanelName" runat="server">
    <ContentTemplate>
         _postback content here_
    </ContentTemplate>
</asp:UpdatePanel>

This was added to the Form Template for one of the Forms and List pages.
Then looking at the table [TabModuleSettings] I identied which TabModuleID this code was created on.

I then wrote the following code with:
<IDOfFormTemplate> as the value of the Tab the Form was saved
<Form&ListModID> as the value of Module ID of Forms and List Module on the system.

Running this added the Form template for all the pages.

SQL Script:
DECLARE
@Setting nvarchar(MAX);

Set @Setting = (SELECT SettingValue FROM [TabModuleSettings] WHERE TabModuleID = <IDOfFormTemplate> AND [SettingName] = 'FormTemplate');

INSERT INTO [dbo].[TabModuleSettings]
([TabModuleID],[SettingName],[SettingValue],[CreatedByUserID],[CreatedOnDate],[LastModifiedByUserID],[LastModifiedOnDate])
SELECT [TabModuleID],'FormTemplate', @Setting, 
664, GETDATE(), 663, GETDATE()
  FROM [dbo].[TabModules] tm
  WHERE [ModuleID] IN (SELECT [ModuleID] FROM [dbo].[Modules] 
										WHERE [ModuleDefID] = <Form&ListModID>)
  AND tm.TabModuleID not in (SELECT TabModuleID FROM [dbo].[TabModuleSettings]
										WHERE [SettingName] = 'FormTemplate')
  ORDER BY tm.TabModuleID;

INSERT INTO [dbo].[TabModuleSettings]
([TabModuleID],[SettingName],[SettingValue],[CreatedByUserID],[CreatedOnDate],[LastModifiedByUserID],[LastModifiedOnDate])
SELECT [TabModuleID],'EnableFormTemplate', 'True', 
664, GETDATE(), 663, GETDATE()
  FROM [dbo].[TabModules] tm
  WHERE [ModuleID] IN (SELECT [ModuleID] FROM [dbo].[Modules] 
										WHERE [ModuleDefID] = <Form&ListModID>)
  AND tm.TabModuleID not in (SELECT TabModuleID FROM [dbo].[TabModuleSettings]
										WHERE [SettingName] = 'EnableFormTemplate')
  ORDER BY tm.TabModuleID;

**Comment by SCullman** [comment]
Can you please try this:

- Open settings/extensions in Persona bar
- Edit Form and List
- Goto Tab "Extenion settings" , Area "Module defintions"
- Edit Form and List
- Inside Module Controls, edit "Edit Userdefined Table"
![image](https://user-images.githubusercontent.com/5693190/62821222-e89fdc00-bb71-11e9-9d97-f24a8d78e516.png)
- Switch on Supports Partial Rendering

This should wrap the whole edit form with an updatePanel

Anyway, I am not able to help here, as I can't reproduce the isue on my own.

**Comment by valadas** [comment]
I am closing this issue due to lack of response for more than a year
