### ISSUE TITLE
Unable to install latest Form and List Module (6.5.4) with DNN 9.01.01

### ISSUE THREAD

**Issue by leearosner** [DNNCommunity/DNN.FormAndList#69]
Presently have Form and List Module 6.5.0 installed. Unable to upgrade to 6.5.4. Install stops at 95%. Using DNN 9.01.01. Net Framework Version 4.6

![2020-01-04_164518](https://user-images.githubusercontent.com/16061520/71772015-c9835b80-2f11-11ea-8c82-1254ad8a8303.jpg)

Any suggestions to complete install would be appreciated.

**Comment by valadas** [comment]
I see your zip file name is Dnn.FormAndList-development.zip, where did you get that file, this is not the file name from the official release...

**Comment by leearosner** [comment]
Perhaps I'm downloading the wrong file. I selected download zip file from the code page. See screenshot below. The downloaded file is "DNN.FormAndList-development.zip"????

![2020-01-05_180418](https://user-images.githubusercontent.com/16061520/71787480-5a2b6b80-2fe6-11ea-8b43-f2baab3e2291.jpg)

Please advise.

**Comment by jncraig** [comment]
You want to click on "releases" just above the green/purple/red bar and download from there.

**Comment by valadas** [comment]
Ha that would be the source code, please do as @jncraig said, I am closing the issue for now, but after trying the proper file if you still have issues please comment or open a new one.
