### ISSUE TITLE
9.2.2 issue trying to add existing form and list module to new pate

### ISSUE THREAD

**Issue by rdh755** [DNNCommunity/DNN.FormAndList#74]
## Describe the bug
When I tried to add a existing form and list module to a new page, I was granted the following popup error 'Error occurred when request service 'AddModule'.' Could this be due to DNN and the module not playing nice w/ each other? 

## To Reproduce
1. Go to a DNN 9.2.2 instance
2. Add a form and list module and configure it work as intended. Should be on home page
3. Create a new page
4. Append existing form and list module on home page.
5. Error occurs.

## Expected behavior
It should add the form and list module. Not produce an error.

## Error log
**Note: Debug DLL's**
No error logs were found when the error comes up.

## Additional context
If the error does not come up in later versions of DNN 9, please let the users know.

**Comment by rdh755** [comment]
Tested this on DNN 9.4.4 and it still comes up.

**Comment by jncraig** [comment]
You might want to turn off popups (you have to do this in SQL I think.

You might want to look at Admin Log and the separate log4net log to see if
there are some clues there.

You should also try this on a page that has the Xcillion skin applied to
see if it's a skin problem.

**Comment by rdh755** [comment]
Tried it on Xcilion skin as well other skins. Problem isn't a skin issue but w/ DNN.
I've even turned off popups thru SQL. Still shows up.
I'm doing this on a brand new DNN local instance, so there isn't a lot of log issues. When the error comes up, there's no admin log.

The issue comes up when adding an existing form and list module to a new page. It comes up only once. After a page refresh, the module is on the page and not floating. Could this be due to some miscommunication between the module and dnn?

**Comment by rdh755** [comment]
When checking my browser console, when the error occurs, I'm seeing the following error:
VM1885:1 POST http://www.dnntest95b.me/API/internalservices/controlbar/AddModule 500 (Internal Server Error).

Could this issue be due to an ongoing issue w/ DNN and the module?

**Comment by SCullman** [comment]
Can you please verify for othertypes of modules? This doesn't look like to be FnL only.

**Comment by valadas** [comment]
I am closing this issue due to no response for multiple months
