### ISSUE TITLE
Part of button doesn't call click event when too big filename chosen for image column value on upload.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [DNNCommunity/DNN.FormAndList#75]
## Describe the bug
When you have column type Image and you want to upload file and you chose one file with long name and then you want' to upload different file, button becomes very wide and it's clickable but click event is called only in the right corner.

## To Reproduce
1. Go to "Form and List Configuration"
2. Add column with type Image
3. Click "Save Configuration and Return"
4. Click "Add New Record"
5. Click "File (A File on Your Site)"
6. Click "Upload New File"
7. Click "Choose File"
8. Choose file from your pc with long name (tested with length of 36 characters)
9. Click left corner of the button, that now has the name of the file - nothing happens
10. Click right corner of the button, that now has the name of the file - it works properly

## Expected behavior
I expected the click on any part of button with the name of the file work the same way.

## Screenshots
![8G2HkeEpvx](https://user-images.githubusercontent.com/21691213/83904922-6ec48900-a769-11ea-84b6-8f8c930a709d.png)

## Error log
N/A

## Additional context
-

**Comment by valadas** [comment]
I cannot reproduce on the default theme, my guess is this is something theme related...
