### ISSUE TITLE
More settings for column type Image

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [DNNCommunity/DNN.FormAndList#76]
## Is your feature request related to a problem?
It might be necessary to restrict user from certain actions, for instance:

- upload only certain types of images
- restrict minimum or/and maximum image size that could be uploaded
- choose whether image can be only url, only on server or both
- whether user is allowed to choose folder where images will be stored for this module instance

## Describe the solution you'd like
Additional settings for column of type Image:

- Types of files (empty = any)
- Min. width
- Min. length
- Max. width
- Max length
- Image location [radiobuttons or dropdownlist]:
  - existing
  - url
  - both
- Allow user to choose folder for images
- Default folder for images (if user is not allowed to choose folder)

## Describe alternatives you've considered
NDA

## Additional context
NDA

**Comment by valadas** [comment]
This would required quite some effort, I am closing this issue as nobody submitted an code for it after multiple months, but if anyone has intentions to do so, please comment and I will be glad to re-open
