### ISSUE TITLE
Fields no longer populate in 6.5.4 after update to DNN 9.8.0

### ISSUE THREAD

**Issue by TopCat6** [DNNCommunity/DNN.FormAndList#80]
## Describe the bug
In Email Settings a column name in a field no longer works after DNN update from 9.7.2 to 9.8.0. For example, putting [Email] into the CC: field in Settings for a defined field called Email used to populate that field and cause a copy to be sent to the originator. Since update to DNN 9.8.0 it no longer does. Same goes for ReplyTo: field. This has now been tested on several sites.

## To Reproduce
1. Go to 'Email Settings' in Page Related Settings of Form and List Configuration
2. Add one of your field names in one of the email header fields
3. Save and then fill out the form.
4. Receive the email and note that the field you asked for is not present in the email.

## Expected behavior
FnL would work in DNN 9.8.0 as it does in DNN 9.7.2

## Screenshots
![image](https://user-images.githubusercontent.com/17517455/99839184-2a625500-2b1f-11eb-94ee-0da811908617.png)

![image](https://user-images.githubusercontent.com/17517455/99839540-ba080380-2b1f-11eb-8c98-c96482167aea.png)

## Error log
No Admin Log entries found

**Comment by valadas** [comment]
Quick question to try and spot the issue, was this just an upgrade to 9.8.0 or in addition the option Telerik removal was performed on this site ?

**Comment by TopCat6** [comment]
Good point!  However, it is one site of each. One site was upgraded to 9.8.0 **and** in addition, the optional Telerik removal was performed on this site. Another site has the Telerik Identifier installed, but is waiting to perform the 9.8 procedure until the issue with the Dnn.Modules.Newsletters.dll module is resolved. So one of each.

**Comment by valadas** [comment]
I just ran a test on 9.8.1 and it all works as expected, however the emails need to be different. It looks like it de-duplicates what makes no sense (like having the same email TO and CC or BCC...

If there is more to it than this, please add more details and I will re-open...

**Comment by TopCat6** [comment]
Looks like https://github.com/dnnsoftware/Dnn.Platform/issues/4472 will fix it.
**BCC and CC are completely ignored when sending email**
and https://github.com/dnnsoftware/Dnn.Platform/issues/4502
**Email ReplyTo is ignored when sending Email**
