### ISSUE TITLE
Rich Text Editor missing

### ISSUE THREAD

**Issue by CubeDweller** [DNNCommunity/DNN.FormAndList#87]
Hi All.

Using FnL 6.5.4 on DNN 8

Have several Form and Lists with a "Rich Text (HTML)" type field.
When logged in as Admin and edit all works good.
But when logged in as a normal user and edit it's just a text box. 

Saw some really old forum post mentioning this problem, but with no answer.

In case it plays a part, we use the CKeditor.

How can I fix this??
Thanks, CD

**Comment by CubeDweller** [comment]
Still looking hard for a solution.

Here are items from the old forum, they sound similar to my problem. However no clear answers
Though some mention anonymous access; what I see is that only the superuser gets the Rich text editor. All my other (logged in) users just get a textbox. Please help if you know how, our new site relies on Form & List; and this issue is a project killer.

https://www.dnnsoftware.com/forums/forumid/56/threadid/356759/scope/posts
https://www.dnnsoftware.com/forums/forumid/56/threadid/536109/scope/posts
https://www.dnnsoftware.com/forums/forumid/56/threadid/359502/scope/posts
https://www.dnnsoftware.com/forums/threadid/384773/scope/posts/rich-text-editor-colum
https://www.dnnsoftware.com/forums/threadid/324612/scope/posts/not-showing-rich-text-box-for-end-users
https://www.dnnsoftware.com/forums/forumid/56/threadid/240338/scope/posts

Thanks, CD

**Comment by CubeDweller** [comment]
OK I believe I found/fixed it.
Under the Module settings, F&L Settings Tab:
There is a checkbox for "Filter entry for markup code or script input. Note: filtering is always enabled for Anonymous users." For some reason that was checked on all our existing instances of F&L.
After unchecking it on one (and saving) the HTML editor shows up for my regular user.

I'm "guessing" that checkbox is so ‘regular editors’ can’t submit html markup in your textboxes; however that option then kills the html editor as well.

Need to tweak the remaining modules, but If holds true, I'll mark the issue closed tomorrow.

Thanks, CD

**Comment by valadas** [comment]
One word of warning though is that to be very careful if you disable that option and the module is accessible to regular users to not open the door to XSS attacks.
