### ISSUE TITLE
Cant push traslation for module

### ISSUE THREAD

**Issue by ufoloko** [DNNCommunity/DNN.FormAndList#89]
I have all resources translated in es-ES localization, but .gitignore file exclude translated files. What is the better option to manage translations for module, maybe another project?

Please confirm

**Comment by valadas** [comment]
It should be here https://www.dnn-connect.org/community/translations it looks like the site is currently under maintenance though

**Comment by valadas** [comment]
That being said, I am not against having more than one language in the project repository unless anyone else has a strong opinion about it ? I can contribute French if nobody indicates a strong argument against it...
