### ISSUE TITLE
How do we make Custom Data Types

### ISSUE THREAD

**Issue by CubeDweller** [DNNCommunity/DNN.FormAndList#92]
This is not an "Issue" but I don't know where else to ask. The old forums to ask these type of question are all dead.

Basically we want to put a drop down on the form that will likely be populated with an SQL query. With the specific options made available according the the user roles. 

That aside, all the old forums would end with the suggestion to create a "custom data type"; But not **how** to do that.

I found a very old example in the Wayback machine. But that no longer works because it is in VB?
https://web.archive.org/web/20110208205916/http://www.formandlist.com/blog.aspx?id=16011

So, is there a modern working example how to create a custom data type? Would that use C#?
Please help
CD

**Comment by jncraig** [comment]
The forums at dnncommunity.org are a perfect place for non-issue questions.

**Comment by CubeDweller** [comment]
Thanks jncraig. Didn't know that was alive, all my searches went to the previous forums.
I'll ask there. But will check back here too just in case.

**Comment by CubeDweller** [comment]
Ok I posted over there. Please let me know there if you can help. So far nothing :(
https://dnncommunity.org/forums/aft/2490

I'll close this here...
