### ISSUE TITLE
Can't hide the Show records button to All Users (I'm desperate)

### ISSUE THREAD

**Issue by gvborre** [DNNCommunity/DNN.FormAndList#95]
## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

**Comment by valadas** [comment]
Well, this is a very vague issue, please follow the issue template and give some information to get into that situation. This is not supposed to happen normally and does not happen for me, so we need some details to make it happen
