### ISSUE TITLE
Need to insert data from master list to personal list. Can I do it via URL to auto fill the add new record form of the personal list?

### ISSUE THREAD

**Issue by GAMacky** [DNNCommunity/DNN.FormAndList#97]
I've got a master list of items and would like to be able to add a button on that master list to add the item to a personal list. I'm trying to not have the user fill out the add record form. I'm trying so that when the user clicks on "Add to my list" button, the item in the master list will then be populated into the personal list. The best way I can see this happening using just the Form and List module is to use a URL with query strings to populate the add a record form for the personal list. Can this be done? If so how should I compose the URL and the query string?

P.S., I'm using Forms and Lists version 6.5.4 on DNN 9.1.1.

**Comment by hismightiness** [comment]
Maybe someone else might have a different answer for you, but I think you'd be better off using a more contemporary structured content solution, like OpenContent (also 2sxc, Live Visualizer, XMod, etc.).  This would allow you to have a lot more flexibility to accomplish this and many other use cases like it.  :)
