### ISSUE TITLE
Import CSV Failure

### ISSUE THREAD

**Issue by johnwolf82** [DNNCommunity/DNN.FormAndList#98]
## Describe the bug
Importing a CSV file to a list terminates with a "Column '' does not belong to table UserDefinedTable."

## To Reproduce
1. Create a list of four columns
2. Create a CSV of four columns and add a few rows
3. From the module menu, choose import CSV
4. Page/module aborts with error: "Column '' does not belong to table UserDefinedTable."

## Expected behavior
Rows are added to the list 

## Screenshots
![image](https://user-images.githubusercontent.com/104915406/166707561-416c4d18-32e1-4322-9748-716f648d20b5.png)

## Error log
**Note: Debug DLL's**
Not sure where to find this

Paste the error log that is related to this issue.

## Additional context
Thank you. Appreciate any direction on how to troubleshoot

**Comment by valadas** [comment]
Cannot reproduce, @johnwolf82 can you link a csv file here as an example of a file that refuses to import. I'll be happy to reopen this issue then and re-test.
